@startwbs

' !define LIGHRED
' !includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml


* Project Iteration n
** Analysis
** Design
*** System Design
** Implementation
*** Build
*** Reaction
**** Health authorities drug information
**** National Patient Record System
**** PHE's single sign-on authentication system
**** Prescription system
**** Health service appointments system
** Testing
*** Verification
*** Validation
** Deployment


@endwbs